- pom.xml
- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandAttachmentsIT.java
- src/main/java/se/sundsvall/supportmanagement/integration/messaging/MessagingClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/messaging/configuration/MessagingConfiguration.java
- src/main/java/se/sundsvall/supportmanagement/integration/messaging/configuration/MessagingProperties.java
- src/main/java/se/sundsvall/supportmanagement/integration/notes/NotesClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/notes/configuration/NotesConfiguration.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandAttachmentService.java
- src/main/resources/application-it.properties
- src/main/resources/application-junit.properties
- src/main/resources/application.properties
- src/main/resources/integrations/messaging-api.yaml
- src/test/java/se/sundsvall/supportmanagement/integration/messaging/configuration/MessagingConfigurationTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/messaging/configuration/MessagingPropertiesTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/notes/configuration/NotesConfigurationTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandAttachmentServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandAttachmentMapperTest.java
- Added messaging integration
- Updated to latest version of dept44
> UF-4291: Added messaging integration

- pom.xml
- src/integration-test/resources/ErrandCommunicationIT/__files/test01_sendEmail/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test02_sendEmailWithAttachments/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test02_sendEmailWithAttachments/request.json
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/EmailRequest.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/AttachmentRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/ErrandsRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/TagRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/messaging/MessagingClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/notes/NotesClient.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapperTest.java
- Added base 64 encoding for incoming html message if the message is not interpreted as already encoded
> UF-4443: Added base 64 encoding for incoming html message

- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Errand.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/ValidCategoryTag.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/ValidTypeTag.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/impl/ValidCategoryTagConstraintValidator.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/impl/ValidTypeTagConstraintValidator.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsCreateResourceFailureTest.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsUpdateResourceFailureTest.java
- src/test/java/se/sundsvall/supportmanagement/api/validation/impl/ValidCategoryTagConstraintValidatorTest.java
- src/test/java/se/sundsvall/supportmanagement/api/validation/impl/ValidTypeTagConstraintValidatorTest.java
This reverts commit 42e46ff74e4482b3d4cdda5edf8fb6d1dcd7d5b7.
> Revert "UF-4535: Remove validation on category and type for errands"

- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/main/resources/integrations/messaging-api.yaml
- src/main/resources/integrations/notes-api.yaml
- Stepped messaging integration to version 2.8
- Stepped notes integration to 2.1
> UF-4784: Stepped versions for integrations

- src/integration-test/resources/ErrandCommunicationIT/__files/test01_sendEmail/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test02_sendEmailWithAttachments/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test03_sendSms/mappings/api-messaging-send-sms.json
- src/main/java/se/sundsvall/supportmanagement/integration/messaging/MessagingClient.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/main/resources/integrations/messaging-api.yaml
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapperTest.java
- Stepped to version 3.0 of messaging integration
- Added async parameter to messaging endpoints with setting to make asyncronous requests
> Uf 4834 step messaging integration version

- src/main/java/se/sundsvall/supportmanagement/api/RevisionResource.java
- src/main/java/se/sundsvall/supportmanagement/integration/notes/NotesClient.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandAttachmentService.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/main/java/se/sundsvall/supportmanagement/service/RevisionService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandNoteMapper.java
- src/main/resources/application.properties
- src/main/resources/integrations/notes-api.yaml
- src/test/java/se/sundsvall/supportmanagement/api/RevisionResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandAttachmentServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/RevisionServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandNoteMapperTest.java
- Updated to version 3.1 of notes integration
- Implemented logic to read and compare note revisions
> UF-5000: Implemented diff logic for errand notes

- src/main/java/se/sundsvall/supportmanagement/api/model/revision/deserializer/RawDataDeserializer.java
- src/test/java/se/sundsvall/supportmanagement/api/model/revision/deserializer/RawDataDeserializerTest.java
- Separated carriage return characters to support both Windows and Linux environments
> UF-5053: Separated unwanted carriage return characters

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandAttachmentsIT.java
- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandNotesIT.java
- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandsIT.java
- src/integration-test/resources/ErrandAttachmentsIT/__files/test03_createErrandAttachment/mappings/api-eventlog-createEvent.json
- src/integration-test/resources/ErrandAttachmentsIT/__files/test04_deleteErrandAttachment/mappings/api-eventlog-createEvent.json
- src/integration-test/resources/ErrandNotesIT/__files/test03_createErrandNote/mappings/api-notes-createNote.json
- src/integration-test/resources/ErrandNotesIT/__files/test04_updateErrandNote/mappings/api-notes-updateNoteById.json
- src/integration-test/resources/ErrandNotesIT/__files/test05_deleteErrandNote/mappings/api-notes-deleteNoteById.json
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/mappings/api-eventlog-createEvent.json
- src/integration-test/resources/ErrandsIT/__files/test05_patchErrand/mappings/api-eventlog-createEvent.json
- src/integration-test/resources/ErrandsIT/__files/test06_deleteErrand/mappings/api-eventlog-createEvent.json
- src/main/java/se/sundsvall/supportmanagement/Constants.java
- src/main/java/se/sundsvall/supportmanagement/api/filter/ExecutingUserSupplier.java
- src/main/java/se/sundsvall/supportmanagement/integration/notes/NotesClient.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandAttachmentService.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandNoteService.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/test/java/se/sundsvall/supportmanagement/api/filter/ExecutingUserSupplierTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandAttachmentServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandNoteServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandServiceTest.java
- Extended service with filter for reading and populating eventlog with executing user sent as header value from client
> UF-5226: Added possibility to supply executing user from client

- src/main/java/se/sundsvall/supportmanagement/integration/db/LabelRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/LabelEntity.java
- src/main/resources/db/migration/V6_5__add_label_table.sql
- src/test/java/se/sundsvall/supportmanagement/integration/db/LabelRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/LabelEntityTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-junit.sql
- added new database table for storing label structures for a namespace and municipality
> UF-5832: Added new table for storing label structures

- src/main/java/se/sundsvall/supportmanagement/api/MetadataLabelResource.java
- src/main/java/se/sundsvall/supportmanagement/api/MetadataResource.java
- src/main/java/se/sundsvall/supportmanagement/api/model/metadata/Label.java
- src/main/java/se/sundsvall/supportmanagement/api/model/metadata/Labels.java
- src/main/java/se/sundsvall/supportmanagement/api/model/metadata/MetadataResponse.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/ValidLabelSiblings.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/impl/ValidLabelSiblingsConstraintValidator.java
- src/main/java/se/sundsvall/supportmanagement/service/MetadataService.java
- src/test/java/se/sundsvall/supportmanagement/api/MetadataLabelResourceFailureTest.java
- src/test/java/se/sundsvall/supportmanagement/api/MetadataLabelResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/metadata/LabelTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/metadata/LabelsTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/metadata/MetadataResponseTest.java
- src/test/java/se/sundsvall/supportmanagement/api/validation/impl/ValidLabelSiblingsConstraintValidatorTest.java
- Implemented CRD-API for labels
- Added label structure to resource for fetching all metadatas
- Added skeleton for handling labels in service component
> UF-5833: Implemented CRD-API for labels

- src/integration-test/resources/ErrandCommunicationIT/__files/test01_sendEmail/request.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test04_readCommunications/response.json
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEmailHeaderEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/enums/EmailHeader.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/EmailReaderMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/EmailreaderService.java
- src/main/resources/db/migration/V8_2__add_email_headers_to_communication.sql
- src/main/resources/integrations/emailreader-api.yaml
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEmailHeaderEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/EmailReaderMapperTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-it.sql
- src/test/resources/db/scripts/truncate.sql
And also
uf-6894: Updated EmailReader integration
> uf-6810: Update DB to store EmailHeaders for communication

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/NamespaceConfigIT.java
- src/integration-test/resources/NamespaceConfigIT/__files/test01_getConfig/response.json
- src/integration-test/resources/NamespaceConfigIT/__files/test04_updateConfig/response_after.json
- src/integration-test/resources/NamespaceConfigIT/__files/test04_updateConfig/response_before.json
- src/integration-test/resources/NamespaceConfigIT/__files/test05_getAllConfigsFilteredByMunicipality/response.json
- src/integration-test/resources/NamespaceConfigIT/__files/test06_getAllConfigs/response.json
- src/main/java/se/sundsvall/supportmanagement/api/NamespaceConfigResource.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/NamespaceConfigRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/NamespaceConfigEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/config/NamespaceConfigService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/NamespaceConfigMapper.java
- src/main/resources/db/migration/V8_23__add_displayname_field_to_namespace_config.sql
- src/test/java/se/sundsvall/supportmanagement/api/NamespaceConfigResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/NamespaceConfigRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/NamespaceConfigEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/config/NamespaceConfigServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/NamespaceConfigMapperTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-it.sql
- src/test/resources/db/scripts/testdata-junit.sql
- Extended config entity with display name attribute
- Extended mapper and service to support requests and responses for the namespace config api
- Adjusted namespace config create method to return better error response if creating a namespace config that already exists within provided municipality
- Added IT-tests for new resource
> UF-10005: Extended DB and service layer

- .gitignore
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandAttachmentMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandAttachmentMapperTest.java
> Saved namespace and municipalityId for attachment

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
> Saved namespace and municipalityId for attachments

- src/main/java/se/sundsvall/supportmanagement/service/ErrandAttachmentService.java
> UF-10273: Nullcheck if revisionresult is null

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Parameter.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/AttachmentRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/CommunicationAttachmentRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/ContactReasonRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/EmailWorkerConfigRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/NamespaceConfigRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/ParameterRepository.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/errand/ParameterTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/resources/api/openapi.yaml
Added displayName in parameters
Fixed incorrect Transactional-annotation and added missing circuitbreaker
> UF-10264: Add parameter displayname

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
> UF-10301: Fixed bug in EmailReaderWorker, senderName was empty

- src/main/java/se/sundsvall/supportmanagement/api/validation/impl/ValidSuspensionConstraintValidator.java
- src/test/java/se/sundsvall/supportmanagement/api/validation/impl/ValidSuspensionConstraintValidatorTest.java
> UF-10463: Fixed reset suspension bug

- src/main/java/se/sundsvall/supportmanagement/integration/db/model/listener/ErrandListener.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorkerTest.java
for incoming emails and utgoing autoreplies
> UF-10492: Fixes so the proper subject and messageID is stored

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionScheduler.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionSchedulerTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorkerTest.java
> UF-10509: No longer removes expired suspensions but rather sends a notification

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorkerTest.java
> UF-10599: Correct autoreplied subject to include #

- src/main/java/se/sundsvall/supportmanagement/integration/db/NotificationRepository.java
- src/main/java/se/sundsvall/supportmanagement/service/NotificationService.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorker.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/NotificationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/service/NotificationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorkerTest.java
> UF-10632: Prevent multiple notifications to be created for suspensions

- src/main/java/se/sundsvall/supportmanagement/integration/db/NotificationRepository.java
- src/main/java/se/sundsvall/supportmanagement/service/NotificationService.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorker.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/NotificationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/service/NotificationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorkerTest.java
> UF-10632: Reduce notifications for suspensions

- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Errand.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsCreateResourceFailureTest.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsResourceTest.java
> UF-10754: Add possibility for validation of errand.stakeholder.role

- changelog/openapi-changelog-8.3.txt
> UF-10721: Add API changelog for 8.2 to 8.3

- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Errand.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsCreateResourceFailureTest.java
- src/test/resources/api/openapi.yaml
> UF-10838: Modified API-validation

- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Errand.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/listener/ErrandListener.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsCreateResourceFailureTest.java
- src/test/resources/api/openapi.yaml
> UF-10838: Add API validation

- pom.xml
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsUpdateResourceFailureTest.java
- src/test/resources/api/openapi.yaml
> UF-10840: Added test

- src/main/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationAttachmentEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/webmessagecollector/configuration/WebMessageCollectorProperties.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/ProcessingHealthIndicator.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailProcessingHealthIndicator.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorProcessingHealthIndicator.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorScheduler.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/main/resources/application-junit.yml
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationAttachmentEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/webmessagecollector/configuration/WebMessageCollectorPropertiesTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorSchedulerTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
> UF-10864: Update WebMessageCollectorSheduler to use config in DB

- changelog/openapi-changelog-9.0.txt
- src/integration-test/resources/EmailReaderSchedulerIT/__files/test01_getAndProcessEmails/response.json
- src/integration-test/resources/ErrandsIT/__files/test01_getAllErrandsSortedByTouched/response.json
- src/integration-test/resources/ErrandsIT/__files/test02_getErrandsByFilter/response.json
- src/integration-test/resources/ErrandsIT/__files/test03_getErrandsById/response.json
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/request.json
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/response.json
- src/integration-test/resources/ErrandsIT/__files/test07_getErrandsByLabelFilter/response.json
- src/integration-test/resources/ErrandsIT/__files/test08_getErrandsByParametersFilter/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Stakeholder.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandMapper.java
- src/test/java/se/sundsvall/supportmanagement/api/model/errand/StakeholderTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandMapperTest.java
- src/test/resources/api/openapi.yaml
Remove stakeholder.metadata
Add stakeholder.parameters
> UF-10927: Refactor API

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/integration/webmessagesender/WebMessageSenderClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/webmessagesender/configuration/WebMessageSenderConfiguration.java
- src/main/java/se/sundsvall/supportmanagement/integration/webmessagesender/configuration/WebMessageSenderProperties.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/main/resources/application.yml
- src/main/resources/integrations/webmessagesender.yaml
- src/test/java/se/sundsvall/supportmanagement/integration/webmessagesender/configuration/WebMessageSenderConfigurationTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/webmessagesender/configuration/WebMessageSenderPropertiesTest.java
> UF-10807: Add integration web-message-sender

- src/main/resources/db/migration/V8_32__migrate_stakeholder_metadata.sql
> UF-10932: Add migrationscript

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandsIT.java
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/request.json
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/response.json
- src/integration-test/resources/ErrandsIT/__files/test05_patchErrand/request.json
- src/integration-test/resources/ErrandsIT/__files/test05_patchErrand/response.json
> UF-10930: Updated IT-tests

- src/main/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/ErrandsRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/specification/ErrandSpecification.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/main/resources/db/migration/V8_34__rename_external_case_id_in_communication_entity.sql
- src/test/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/ErrandsRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-it.sql
- src/test/resources/db/scripts/testdata-junit.sql
> UF-10970: Add filter to avoid duplicate web-messages

- src/main/resources/application.yml
> UF-11003: Update file limit

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandCommunicationIT.java
- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandTimeMeasurementsIT.java
- src/integration-test/resources/ErrandCommunicationIT/__files/test09_sendWebMessage/mappings/api-gateway-token.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test09_sendWebMessage/mappings/api-messaging-send-webmessage.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test09_sendWebMessage/request.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/mappings/api-employee-getPersonalData.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/mappings/api-employee-getPersonalData_assignedUserIdX.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/mappings/api-eventlog-createEvent.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/mappings/api-gateway-token.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/mappings/api-messaging-send-webmessage.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/request.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/response.json
- src/integration-test/resources/ErrandsIT/__files/test01_getAllErrandsSortedByTouched/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/EmailAttachment.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/RequestAttachment.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/WebMessageAttachment.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/ParameterEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapperTest.java
- src/test/resources/db/scripts/testdata-it.sql
> UF-10996: Add service logic for seding webmessages

- src/main/java/se/sundsvall/supportmanagement/integration/db/specification/ErrandSpecification.java
> UF-11176: Fix sonarr issue

- src/main/resources/integrations/messaging-api.yaml
> UF-11215: Update messaging API to 5.4

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
Attachment data must be present before saving Communication entity to DB. Refactor to save once instead of twice.
> UF-11217: Fix bug in WebMessageCollectorWorker

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
> UF-11227: Save webmesssage attachments as errend attachments

- src/main/java/se/sundsvall/supportmanagement/api/model/note/CreateErrandNoteRequest.java
- src/main/java/se/sundsvall/supportmanagement/api/model/note/ErrandNote.java
- src/main/java/se/sundsvall/supportmanagement/api/model/note/FindErrandNotesRequest.java
- src/main/java/se/sundsvall/supportmanagement/api/model/note/FindErrandNotesResponse.java
- src/main/java/se/sundsvall/supportmanagement/api/model/note/UpdateErrandNoteRequest.java
- src/test/resources/api/openapi.yaml
> UF-11229: Fix faulty openAPI specification

- src/main/resources/db/migration/V8_35__drop_table_stakeholder_metadata.sql
> UF-11251: Drop table stakeholder_metadata

- src/main/java/se/sundsvall/supportmanagement/integration/db/model/ErrandEntity.java
- src/main/resources/db/migration/V8_36__change_index_for_errand.sql
- src/test/resources/db/scripts/schema.sql
> UF-10961: Update DB index for errand

- src/main/java/se/sundsvall/supportmanagement/integration/emailreader/EmailReaderClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/employee/EmployeeClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/eventlog/EventlogClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/webmessagecollector/WebMessageCollectorClient.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandAttachmentServiceTest.java
> UF-11506: Fixed mixed up circuitbreaker names

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
> UF-11524: Fix bug with wrong file size on email attachments

- pom.xml
- src/integration-test/resources/NotificationIT/__files/test02_getNotificationsByOwnerId/response.json
- src/integration-test/resources/NotificationIT/__files/test03_updateNotification/request.json
- src/integration-test/resources/NotificationIT/__files/test05_getNotificationById/response.json
- src/integration-test/resources/NotificationIT/__files/test06_getNotificationsByErrandId/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/notification/Notification.java
- src/test/java/se/sundsvall/supportmanagement/api/model/notification/NotificationTest.java
- src/test/resources/api/openapi.yaml
> UF-11606: Added notification.globalAcknowledged

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/NotificationIT.java
- src/integration-test/resources/NotificationIT/__files/test01_createNotification/request.json
- src/integration-test/resources/NotificationIT/__files/test03_updateNotification/request.json
- src/integration-test/resources/NotificationIT/__files/test03_updateNotification/response.json
- src/test/resources/db/scripts/testdata-it.sql
> UF-11609: Updated IT-tests for Notification

- src/main/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapper.java
- src/main/resources/db/migration/V8_42__add_column_to_communication_table.sql
- src/main/resources/integrations/messaging-api.yaml
- src/test/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/CommunicationEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapperTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-it.sql
- src/test/resources/db/scripts/testdata-junit.sql
> UF-11710: Added senderId to db-layer and using it when sending web-messages

- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandServiceTest.java
> UF-11827: Remove unnecessary call for findErrands

- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Parameter.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandParameterMapper.java
- src/test/java/se/sundsvall/supportmanagement/api/model/errand/ParameterTest.java
- src/test/resources/api/openapi.yaml
> UF-13868: Added group to Parameter

- src/integration-test/resources/ErrandParametersIT/__files/test01_updateErrandParameters/request.json
- src/integration-test/resources/ErrandParametersIT/__files/test01_updateErrandParameters/response.json
- src/integration-test/resources/ErrandParametersIT/__files/test03_findErrandParameters/response.json
- src/integration-test/resources/ErrandParametersIT/__files/test04_updateErrandParameter/response.json
- src/integration-test/resources/ErrandTimeMeasurementsIT/__files/test03_updateErrandAndGetTimeMeasurements/response.json
- src/integration-test/resources/ErrandsIT/__files/test01_getAllErrandsSortedByTouched/response.json
- src/integration-test/resources/ErrandsIT/__files/test02_getErrandsByFilter/response.json
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/ErrandEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/ParameterEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandParameterMapper.java
- src/main/resources/db/migration/V8_43__add_columns_to_parameter_table.sql
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/ParameterEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandParameterMapperTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-it.sql
> Uf 13866 update db layer and mapping

- src/main/resources/db/migration/V8_43__add_columns_to_parameter_table.sql
> UF-14231: Bug-fix in flyway-script

- src/main/resources/db/migration/V8_43__add_columns_to_parameter_table.sql
> UF-14231: Fix flyway-script again

- src/integration-test/resources/EmailReaderSchedulerIT/__files/test01_getAndProcessEmails/mappings/api-email-reader-getAttachment.json
- src/integration-test/resources/EmailReaderSchedulerIT/__files/test01_getAndProcessEmails/response/api-email-reader-getEmail-response.json
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapperTest.java
> UF-14312: Fix email attachment processing

- src/integration-test/resources/ErrandParametersIT/__files/test01_updateErrandParameters/request.json
- src/integration-test/resources/ErrandParametersIT/__files/test01_updateErrandParameters/response.json
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/request.json
- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/response.json
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandParameterMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandParameterMapperTest.java
> UF-14441: Fix for keeping order of errand parameters

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/api/model/errand/Errand.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/test/java/se/sundsvall/supportmanagement/api/model/errand/ErrandTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandMapperTest.java
- src/test/resources/api/openapi.yaml
> UF-14429: Added notifications to errand in api

- pom.xml
- src/test/resources/api/openapi.yaml
> UF-14433: Fix version

- changelog/openapi-changelog-9.1.txt
- changelog/openapi-changelog-9.2.txt
- changelog/openapi-changelog-9.3.txt
> UF-14446: Added changelogs

- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
> UF-14743: Make sure email is handled properly before sending email

- src/integration-test/resources/ErrandCommunicationIT/__files/test02_sendEmailWithAttachments/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test04_readCommunications/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test06_sendEmailWithErrandAttachment/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/Communication.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/EmailRequest.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/SmsRequest.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/WebMessageRequest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/CommunicationTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/EmailRequestTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/SmsRequestTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/WebMessageRequestTest.java
- src/test/resources/api/openapi.yaml
> UF-14754: Add internal field to communcations

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/api/ErrandCommunicationResource.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/Communication.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepository.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapper.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/CommunicationTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/resources/api/openapi.yaml
- src/test/resources/db/scripts/testdata-junit.sql
> UF-14788: Add new resource to filter external communications

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandCommunicationIT.java
- src/integration-test/resources/ErrandCommunicationIT/__files/test12_readExternalCommunications/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/Communication.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/CommunicationTest.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/resources/db/scripts/testdata-it.sql
> UF-14762: Add IT-test and change viewed to Boolean

- src/main/resources/db/migration/V8_45__update_column_communication_internal.sql
> UF-14888: Update DB communication.internal to default to false

- src/integration-test/resources/EmailReaderSchedulerIT/__files/test01_getAndProcessEmails/mappings/api-eventlog-updateEvent.json
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorkerTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
> UF-14897: Changed notification/event text

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/Constants.java
- src/main/java/se/sundsvall/supportmanagement/api/filter/SentByHeaderFilter.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/WebMessageRequest.java
- src/test/java/se/sundsvall/supportmanagement/api/filter/SentByHeaderFilterTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/WebMessageRequestTest.java
- src/test/resources/api/openapi.yaml
* Added a new attribute to the WebMessageRequest class.
* Version 10.0 -> 10.1
* Added a request filter to store values from X-Sent-By header.
> UF-14790 API changes

- src/integration-test/resources/ErrandNotesIT/__files/test01_findErrandNotes/mappings/api-notes-findNotes.json
- src/integration-test/resources/ErrandNotesIT/__files/test01_findErrandNotes/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test01_findErrandNotes/responses/api-notes-findNotes-response.json
- src/integration-test/resources/ErrandNotesIT/__files/test02_readErrandNote/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test02_readErrandNote/responses/api-notes-findNoteById-response.json
- src/integration-test/resources/ErrandNotesIT/__files/test03_createErrandNote/mappings/api-notes-createNote.json
- src/integration-test/resources/ErrandNotesIT/__files/test04_updateErrandNote/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test04_updateErrandNote/responses/api-notes-updateNoteById-response.json
- src/integration-test/resources/ErrandNotesIT/__files/test05_updateErrandNoteWithoutChanges/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test05_updateErrandNoteWithoutChanges/responses/api-notes-updateNoteById-response.json
- src/main/java/se/sundsvall/supportmanagement/service/ErrandNoteService.java
- src/main/resources/application.yml
- src/test/java/se/sundsvall/supportmanagement/service/ErrandNoteServiceTest.java
- src/test/resources/api/openapi.yaml
> DRAKEN-1128: Change notes clientId to be static

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandCommunicationIT.java
- src/integration-test/resources/ErrandNotesIT/__files/test01_findErrandNotes/mappings/api-notes-findNotes.json
- src/integration-test/resources/ErrandNotesIT/__files/test01_findErrandNotes/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test01_findErrandNotes/responses/api-notes-findNotes-response.json
- src/integration-test/resources/ErrandNotesIT/__files/test02_readErrandNote/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test02_readErrandNote/responses/api-notes-findNoteById-response.json
- src/integration-test/resources/ErrandNotesIT/__files/test03_createErrandNote/mappings/api-notes-createNote.json
- src/integration-test/resources/ErrandNotesIT/__files/test04_updateErrandNote/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test04_updateErrandNote/responses/api-notes-updateNoteById-response.json
- src/integration-test/resources/ErrandNotesIT/__files/test05_updateErrandNoteWithoutChanges/response.json
- src/integration-test/resources/ErrandNotesIT/__files/test05_updateErrandNoteWithoutChanges/responses/api-notes-updateNoteById-response.json
- src/main/java/se/sundsvall/supportmanagement/service/ErrandNoteService.java
- src/main/resources/application.yml
- src/test/java/se/sundsvall/supportmanagement/service/ErrandNoteServiceTest.java
- src/test/resources/api/openapi.yaml
> UF-15051: Change notes clientId to be static

- src/main/java/se/sundsvall/supportmanagement/api/model/communication/EmailAttachment.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/WebMessageAttachment.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/impl/ValidFileSizeConstraintValidator.java
- src/main/resources/application.yml
- src/test/resources/api/openapi.yaml
> UF-15121: increased filesize constraints

- src/main/java/se/sundsvall/supportmanagement/api/validation/ValidFileSize.java
- src/main/java/se/sundsvall/supportmanagement/api/validation/impl/ValidFileSizeConstraintValidator.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/util/BlobBuilder.java
- src/main/resources/application.yml
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/util/BlobBuilderTest.java
> UF-15117: Some optimizations when sending large files

- src/main/java/se/sundsvall/supportmanagement/api/filter/SentByHeaderFilter.java
- src/main/java/se/sundsvall/supportmanagement/api/model/event/Event.java
- src/main/java/se/sundsvall/supportmanagement/api/model/event/EventType.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/ErrandEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/main/java/se/sundsvall/supportmanagement/service/util/SpecificationBuilder.java
- src/main/resources/db/migration/V8_46__add_index_on_errand_labels.sql
- src/test/java/se/sundsvall/supportmanagement/service/ErrandServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/RevisionServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/TimeMeasurementServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/util/BlobBuilderTest.java
- src/test/resources/db/scripts/schema.sql
> UF-15514: Add fix for performance issues and some code cleanup.

- src/main/java/se/sundsvall/supportmanagement/integration/db/model/NotificationEntity.java
- src/main/resources/db/migration/V8_47__add_index_on_owner_id_for_notifications.sql
- src/test/resources/db/scripts/schema.sql
> UF-15507: Add DB index for notification.ownerId

- src/integration-test/resources/ErrandCommunicationIT/__files/test01_sendEmail/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test02_sendEmailWithAttachments/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test03_sendSms/mappings/api-messaging-send-sms.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test06_sendEmailWithErrandAttachment/mappings/api-messaging-send-email.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test09_sendWebMessageUserUnknown/mappings/api-messaging-send-webmessage.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/mappings/api-messaging-send-webmessage.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test11_sendWebMessage/mappings/api-messaging-send-webmessage.json
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
> UF-15467: call messaging synchronously

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/api/model/attachment/ErrandAttachment.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ErrandAttachmentMapper.java
- src/test/java/se/sundsvall/supportmanagement/TestObjectsBuilder.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandAttachmentsResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/attachment/ErrandAttachmentTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandAttachmentMapperTest.java
- src/test/resources/api/openapi.yaml
> UF-15624: add created to ErrandAttachment API

- src/integration-test/resources/ErrandsIT/__files/test04_postErrand/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/notification/Notification.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/NotificationEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/enums/NotificationSubType.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandAttachmentService.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/main/java/se/sundsvall/supportmanagement/service/EventService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/NotificationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/supensions/SuspensionWorker.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/main/resources/db/migration/V8_48__add_notification_subtype_column.sql
- src/test/java/se/sundsvall/supportmanagement/TestObjectsBuilder.java
- src/test/java/se/sundsvall/supportmanagement/api/NotificationsResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/api/model/notification/NotificationTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/NotificationEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/enums/NotificationSubTypeTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandAttachmentServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/EventServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/NotificationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorkerTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
- src/test/resources/api/openapi.yaml
- src/test/resources/db/scripts/schema.sql
Also contains:
[UF-15486: Add notification subtype to entity](https://github.com/Sundsvallskommun/api-service-support-management/commit/3a04787c8f432eee5c7508663c59e8cb4bf9a801)
[UF-15485: Add notification subtype to api model](https://github.com/Sundsvallskommun/api-service-support-management/commit/5e05f9c8c153f1341eee3c8617595b8a2d5c1e0f)
> Uf-15487: Add subtype logic

- changelog/changelog-10.1.md
- changelog/changelog-10.2.md
> UF-15682: Add changelog for 10.2 and 10.1

- src/main/resources/application.yml
> UF-15749: Logbook payload limit should not be set directly in service

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/api/model/config/NamespaceConfig.java
- src/test/java/se/sundsvall/supportmanagement/api/model/config/NamespaceConfigTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/NamespaceConfigMapperTest.java
- src/test/resources/api/openapi.yaml
> UF-15961: Added API-support for new config value

- pom.xml
- src/integration-test/resources/NamespaceConfigIT/__files/test01_getConfig/response.json
- src/integration-test/resources/NamespaceConfigIT/__files/test04_updateConfig/request.json
- src/integration-test/resources/NamespaceConfigIT/__files/test04_updateConfig/response_after.json
- src/integration-test/resources/NamespaceConfigIT/__files/test04_updateConfig/response_before.json
- src/integration-test/resources/NamespaceConfigIT/__files/test05_getAllConfigsFilteredByMunicipality/response.json
- src/integration-test/resources/NamespaceConfigIT/__files/test06_getAllConfigs/response.json
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/NamespaceConfigEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/NamespaceConfigMapper.java
- src/main/resources/db/migration/V8_50__add_column_to_namespace_config.sql
- src/test/java/se/sundsvall/supportmanagement/integration/db/NamespaceConfigRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/NamespaceConfigEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/NamespaceConfigMapperTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-it.sql
- src/test/resources/db/scripts/testdata-junit.sql
> UF-15960: Add config setting 'notificationTTLInDays' in DB

- src/main/resources/db/migration/V8_52__drop_communication_attachment_data.sql
> UF-15872: flywayscript to drop unnused table and corresponding column

- src/main/resources/application.yml
> UF-15675: Removed baseline-flag

- src/main/java/se/sundsvall/supportmanagement/api/ErrandCommunicationResource.java
- src/main/java/se/sundsvall/supportmanagement/service/ConversationService.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandCommunicationResourceFailureTest.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandCommunicationResourceTest.java
- src/test/resources/api/openapi.yaml
> UF-16311: Added getConversationMessageAttachment-resource in the API

- src/main/java/se/sundsvall/supportmanagement/integration/db/ConversationRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/MessageExchangeSyncRepository.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/MessageExchangeSyncEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/communication/ConversationEntity.java
- src/main/java/se/sundsvall/supportmanagement/integration/messageexchange/MessageExchangeClient.java
- src/main/java/se/sundsvall/supportmanagement/service/ConversationService.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeScheduler.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeWorker.java
- src/main/resources/application-it.yml
- src/main/resources/application.yml
- src/main/resources/db/migration/V1_3__add_column_in_conversation_tabel.sql
- src/main/resources/db/migration/V1_4__message_exchange_sync_data.sql
- src/test/java/se/sundsvall/supportmanagement/integration/db/ConversationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/MessageExchangeSyncRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/MessageExchangeSyncEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/communication/ConversationEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeSchedulerTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeWorkerTest.java
- src/test/resources/db/scripts/schema.sql
- src/test/resources/db/scripts/testdata-junit.sql
- src/test/resources/db/scripts/truncate.sql
> UF-16592: Add scheduled job for message exchange

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/integration/messaging/MessagingClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/messagingsettings/MessagingSettingsClient.java
- src/main/java/se/sundsvall/supportmanagement/integration/messagingsettings/configuration/MessagingSettingsConfiguration.java
- src/main/java/se/sundsvall/supportmanagement/integration/messagingsettings/configuration/MessagingSettingsProperties.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/ConversationService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/main/resources/application.yml
- src/main/resources/integrations/messaging-settings-api.yaml
- src/test/java/se/sundsvall/supportmanagement/integration/messagingsettings/configuration/MessagingSettingsConfigurationTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/messagingsettings/configuration/MessagingSettingsPropertiesTest.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ConversationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapperTest.java
> UF-16628: messaging-settings integration

- src/main/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/MessagingMapperTest.java
> UF-16660: correct parse of mailbody for conversation mail message

- src/integration-test/java/se/sundsvall/supportmanagement/apptest/ErrandCommunicationIT.java
- src/integration-test/resources/ErrandCommunicationIT/__files/test14_getConversationById/mappings/api-messageexchange-getconversation.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test14_getConversationById/response.json
- src/main/java/se/sundsvall/supportmanagement/service/ConversationService.java
- src/main/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncService.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeScheduler.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/test/java/se/sundsvall/supportmanagement/service/ConversationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeSchedulerTest.java
> UF-16593: Add notification for conversation and refactor sync

- src/main/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncService.java
> Fix nullpointer bug in message exchange sync

- src/main/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncService.java
- src/test/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncServiceTest.java
> Fix filter bug in sync conversation

- src/main/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncService.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorkerTest.java
- Added filter to not send mails to no reply addresses
- Added logging when email is not eligible to send email to
> UF-16673: Added filter for no reply addresses when sending mails

- src/main/java/se/sundsvall/supportmanagement/service/mapper/HibernateProxyAdapter.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/HibernateProxyAdapterFactory.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/RevisionMapper.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/RevisionMapperTest.java
> UF-16723: Add Hibernate proxy adapter for GSON serialization

- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
> MSI-283: dont send messsagenotification if client sent message

- pom.xml
- src/main/java/se/sundsvall/supportmanagement/api/ErrandsResource.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandLabelService.java
- src/main/java/se/sundsvall/supportmanagement/service/NotificationService.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/ConversationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderWorker.java
- src/main/java/se/sundsvall/supportmanagement/service/util/ServiceUtil.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/test/java/se/sundsvall/supportmanagement/api/ErrandsResourceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/MessageExchangeSyncServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/ErrandAttachmentMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/messageexchange/MessageExchangeSchedulerTest.java
- src/test/resources/api/openapi.yaml
> UF-16752: Fix issues.

- src/main/java/se/sundsvall/supportmanagement/service/ConversationService.java
- src/test/java/se/sundsvall/supportmanagement/service/ConversationServiceTest.java
> UF-16940: notifications should only be sent on EXTERNAL conversations

- pom.xml
- src/integration-test/resources/ErrandCommunicationIT/__files/test18_createConversationMessage/mappings/api-messaging-settings-get-sender-info.json
- src/main/java/se/sundsvall/supportmanagement/integration/messagingsettings/MessagingSettingsClient.java
- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/ConversationService.java
- src/main/resources/integrations/messaging-settings-api.yaml
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ConversationServiceTest.java
> UF-17007: update messaging settings integration

- pom.xml
- src/integration-test/resources/ErrandCommunicationIT/__files/test02_sendEmailWithAttachments/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test04_readCommunications/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test06_sendEmailWithErrandAttachment/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test10_sendWebMessageWithAttachments/response.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test12_readExternalCommunications/response.json
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/Communication.java
- src/main/java/se/sundsvall/supportmanagement/integration/db/model/communication/CommunicationEntity.java
- src/main/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapper.java
- src/main/java/se/sundsvall/supportmanagement/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/resources/db/migration/V1_6__add_recipient_table.sql
- src/test/java/se/sundsvall/supportmanagement/api/model/communication/CommunicationTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/CommunicationRepositoryTest.java
- src/test/java/se/sundsvall/supportmanagement/integration/db/model/communication/CommunicationEntityTest.java
- src/test/java/se/sundsvall/supportmanagement/service/mapper/CommunicationMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorMapperTest.java
- src/test/java/se/sundsvall/supportmanagement/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
- src/test/resources/api/openapi.yaml
- src/test/resources/db/scripts/schema.sql
> UF-17069: add list of recipients to communication

- src/main/java/se/sundsvall/supportmanagement/service/CommunicationService.java
- src/main/java/se/sundsvall/supportmanagement/service/ErrandService.java
- src/test/java/se/sundsvall/supportmanagement/service/CommunicationServiceTest.java
- src/test/java/se/sundsvall/supportmanagement/service/ErrandServiceTest.java
> UF-17295: update errand delete to delete everything in DB

- src/main/java/se/sundsvall/supportmanagement/integration/db/model/communication/CommunicationAttachmentEntity.java
> UF-17364: correct cascade for communication_attachment

- src/main/resources/db/migration/V1_8__delete_stakeholders_update_log.sql
> UF-17367: Remove table used for migration logging

- pom.xml
- src/integration-test/resources/ErrandCommunicationIT/__files/test03_sendSms/mappings/api-messaging-send-sms.json
- src/integration-test/resources/ErrandCommunicationIT/__files/test03_sendSms/request.json
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/Communication.java
- src/main/java/se/sundsvall/supportmanagement/api/model/communication/SmsRequest.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandCommunicationResourceFailureTest.java
- src/test/java/se/sundsvall/supportmanagement/api/ErrandCommunicationResourceTest.java
- src/test/resources/api/openapi.yaml
> UF-17393: Change to a fake phone number in test/doc
